name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Erlang, Rebar3 and Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          rebar3-version: "3"
          gleam-version: "1.12.0"

      - name: Run tests
        run: gleam test
